on:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '11 11 3,18 * *'

name: Check API Version

jobs:
  Check-API-Version:
    runs-on: ubuntu-22.04

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install nbar2
        run: |
          install.packages('remotes')
          remotes::install_local()
        shell: Rscript {0}
      - name: Check whether the API has changed
        run: |
           stopifnot(nbar2::nba_check_version())
        shell: Rscript {0}